### ISSUE TITLE
[Suggestion]: Compatibility with Simple Backpack

### ISSUE THREAD

**Issue by faahbio** [Fuzss/easyshulkerboxes#12]
### Suggestion (Required)

Compatibility with the mod Simple Backpack

Two items would be able to use the mod, the backpack and the end backpack

https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric

I'm suggesting it because it makes sense (I think) as it is a 1.5M+ downloads mod

Thanks in advance <3

**Comment by murao-kun** [comment]
Also backpacked support then.

**Comment by Fuzss** [comment]
I'm still working on the internals for supporting other mods, the system should essentially be data-driven when it's fully done so users themselves can add mod support.
Until then though I'll just recommend my own backpack/bag mod which has all the features from Easy Shulker Boxes already and is probably pretty much the same as the backpack from the mod you suggested otherwise.
https://www.curseforge.com/minecraft/mc-mods/bag-of-holding-forge

**Comment by faahbio** [comment]
> I'm still working on the internals for supporting other mods, the system should essentially be data-driven when it's fully done so users themselves can add mod support. Until then though I'll just recommend my own backpack/bag mod which has all the features from Easy Shulker Boxes already and is probably pretty much the same as the backpack from the mod you suggested otherwise. https://www.curseforge.com/minecraft/mc-mods/bag-of-holding-forge

Thanks man, I didn't see u had a mod for that, I'm adding it to my mods, good job

**Comment by Fuzss** [comment]
It actually still has the dupe bug with the last item though you reported earlier here, I’ll fix that later.

**Comment by murao-kun** [comment]
I will be looking for data-driven support, that is amazing news to hear! Thank you!
