### ISSUE TITLE
[Bug]: Easy Shulker Boxes breaks Mouse Wheelie

### ISSUE THREAD

**Issue by UnZkiPriimE** [Fuzss/easyshulkerboxes#15]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

19.2

### Mod Version (Required)

4.3.7

### Notes (Required)

Mouse wheelie enhances inventory management, in theory ESB would be an awesome addition, unfortunately when using both mods, Mouse Wheelie breaks. Quitting the world and rejoining is required to fix it.

Expected behavior: When I scroll on the Shulker Box it should move in the inventory like every other item and in Creative it should get deleted (which it doesn't).

I don't know if this is something you can fix or the Mouse Wheelie creator has to do, but since you both improve a somewhat similar aspect, I think it would be great if both worked together.

**Comment by Fuzss** [comment]
Mouse Wheelie completely overrides the scrolling behavior from Easy Shulker Boxes, so what you're seeing all comes from that mod.

So apparently Mouse Wheelie has a bug when trying to move bundle-like items (items that support inventory interactions). Instead of the item (bundle) being moved, contents are extracted one-by-one and moved instead. This can be observed with just Mouse Wheelie installed, when interacting with a filled bundle.

Since Easy Shulker Boxes simply enables bundle behavior for shulker boxes, they are problematic, too, now. I'll make a report for Mouse Wheelie.

**Comment by UnZkiPriimE** [comment]
okay thanks, awesome response

**Comment by Fuzss** [comment]
Also due to the way Mouse Wheelie is implemented, even when the extracting items bug is fixed, the scrolling inside of containers from Easy Shulker Boxes still won't work with it. There isn't really anything I can do about that, I use Fabric Api's mouse events, Mouse Wheelie hooks in way before that.

In case you are interested in an alternative that fully works with Easy Shulker Boxes you could check out this mod: https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks
