### ISSUE TITLE
[Bug]: Chests are Shulker Boxes

### ISSUE THREAD

**Issue by notIkibo** [Fuzss/easyshulkerboxes#30]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.4.1

### Notes (Required)

While taking an item into drag mode, I was a + next to my chest that was in my inventory. I took away some functionalities (like scrolling) and it corresponded with the chest. So I deactivated EasyShulkerBoxes and my chest were normal too.

Everywhere in the configs, it says "Container", never "Shulker Box".
Is it intentional or a bug?

This is (hopefully) a bug and gets a fix 👉👈

**Comment by Fuzss** [comment]
This is intentional in creative mode. Easy Shulker Boxes affects ender chests, bundles, backpacks and most container in creative mode, too, despite the name.

If you don‘t want chests to be affected you can probably use a custom data pack with the filter section configured to exclude those data files from the built-in data pack.

**Comment by notIkibo** [comment]
Oh nvm, if that's creative only: I'm fine with that. I could be useful indeed. Thank you for clarifying!
