### ISSUE TITLE
[Bug]: Some aspects of gameplay feel unintuitive and tedious, and config isn't displaying using Mod Menu

### ISSUE THREAD

**Issue by kurocat471** [Fuzss/easyshulkerboxes#37]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

Playing on survival, I'm always putting shulkers into and taking them out of my ender chest, but currently, right-clicking an ender chest while holding a shulker tries to put the ender chest into the shulker instead of vice-versa. There's no way to put a shulker into an ender chest while holding the shulker, and it interrupts gameplay, as you would often leave one ender chest in your inventory and manage shulkers elsewhere. On top of this, in this example, if you have multiple ender chests in your inventory, you must only be holding one to put other containers into them, otherwise it will try to put the ender chests into the shulker no matter what. In addition, there seems to be no way to put multiple items into a container at once, as right-clicking and dragging over multiple items just puts them in the container then immediately spits them back out in the same slot - presumably because it checks whether there's a filled slot under your cursor before checking for an empty one, as taking out items this way works fine. I would look at the config to see if there's an option there to fix any of these, but config seems to not be displaying within Mod Menu (the one suggested on your modpage). If this isn't supported anymore or there's no config to change, the modpage should be updated to show that. Also, something smaller I'd like to see but isn't required: empty shulker boxes have no way of showing their empty inventories, even when holding ALT (the hotkey that's supposed to force any shulker to show its inventory). Even though it'd be mostly useless, it feels inconsistent to not have that as a feature. Sorry if this should listed be under suggestion instead of bug, I'm not sure how much of this is intentional.

**Comment by kurocat471** [comment]
After testing a bit, regarding the last part: it seems shulkers with no NBT data don't ever show their inventory in tooltips, while ones with NBT, even if empty, do. When breaking an empty shulker box, it drops an empty box WITH NBT data, but when crafting one or emptying it using the features of this mod, it returns an empty shulker box with NO NBT data. For consistency, emptying a shulker using this mod should return an empty box with no NBT data, but also, all empty boxes should be treated the same, regardless of having NBT: with no tooltip unless ALT (the hotkey to display a shulker's full inventory) is held.

**Comment by AstudilloMarillo** [comment]
I agree with the overall sentiment. For a while I was confused as to how to put a shulker box into an ender chest since I always pick up the item I want to store and right-click the container, instead of the other way around. I'd like an option to be able to flip the interaction of shulker boxes vs ender chests.

**Comment by Fuzss** [comment]
1. For the ender chest, this is not really possible to change without rewriting much. Vanilla logic gives precedence to the item carried by the cursor, so if that item offers any interactions they are processed first, only afterward the item in the hovered slot is checked. And generally I think that behavior is quite intuitive, only the ender chest being an edge case that's not really possible to easily untangle from the rest. So that won't change.
2. The items being spat back out after being dragged over is a mod conflict, maybe you have Mouse Tweaks installed? Easy Shulker Boxes uses Forge / Fabric events everywhere for the new interactions, if other mods do not use those events or ignore them there is nothing I will do about it, that's up to those mods.
3. Empty inventories showing for shulker boxes that have been placed down at some point is not ideal, I'll disable that in a future release.
4. All configs are registered for the Item Interactions / Puzzles Api mod since that is the core library behind all functionality which is shared by multiple mods.
